language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: osx
      osx_image: xcode9.2

before_install: ./travis-ci/before_install.sh
before_script: ./travis-ci/before_script.sh
script: ./travis-ci/script.sh
after_failure: ./travis-ci/after_failure.sh

notifications:
  email: false
